services:
  
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: devFlex360
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: databasePassword
    healthcheck:
      test: "pg_isready -q -h db"
      interval: 10s
      retries: 5
      timeout: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: senha
    ports:
      - 8085:80
    
  flex360-api:
    
    depends_on:
      db:
        condition: service_healthy
  
    build: .
    container_name: flex360-api  
    restart: always
    command: >
      java -jar app.jar