name: build and deploy spring-api
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test Spring API
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 22

      - name: Setup Maven
        run: sudo apt-get install -y maven

      - name: Run unit tests
        run: mvn -B test --file pom.xml
        
      - name: Build the app
        run: |
          mvn clean
          mvn -B package --file pom.xml

  docker-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    needs: build-test  
    if: github.ref == 'refs/heads/main' 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 22

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flex360-api:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push the Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flex360-api:latest
